name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - env: "latest"
            python: "3.13"
          - env: "oldest"
            python: "3.9"

    steps:
      - uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Run tests
        run: uvx hatch -e ${{ matrix.env }} run tests
